drop table if exists products;
create table products (
  id integer generated by default as identity(start with 1) primary key,
  sku integer NOT NULL,
  name varchar(100) NOT NULL,
  price double NOT NULL,
  mrp double NOT NULL,
  description varchar(500) NOT NULL,
  packing varchar(50) NOT NULL,
  image varchar(200) DEFAULT NULL,
  category integer NOT NULL,
  stock integer NOT NULL,
  status varchar(10) NOT NULL
);

--
-- Dumping data for table `products`
--

INSERT INTO products (id, sku, name, price, mrp, description, packing, image, category, stock, status) VALUES
(138, 5053, 'Aramusk Bath Soap For Men   ', 108, 108, '', '3 X 125 g ', 'aramusk-bath-soap-for-men-3-x-125-g.png', 140, 100, 'Active'),
(248, 386, 'Adidas Deo Ice Dive Deo Body Spray   ', 199, 199, '', '150 ml ', 'adidas-adidas-body-deo-ice-dive-150-ml.png', 130, 20, 'Inactive'),
(318, 6124, 'Baba Ramdev Patanjali Anti Bacterial Herbal Hand Wash Refill   ', 40, 40, '', '200 ml ', 'baba-ramdev-patanjali-anti-bacterial-herbal-hand-wash-refill-200-ml.png', 160, 50, 'Inactive'),
(432, 5625, 'Adidas Ice Dive Shower Gel   ', 150, 150, '', '250 ml ', 'adidas-ice-dive-shower-gel-250-ml.png', 170, 0, 'Active'),
(448, 2298, 'Axe Denim Cologne Talc   ', 115, 115, '', '300 g ', '1327941212-Jan30-1147.png', 180, 0, 'Active'),
(490, 8909, 'All Out Off Family Insect Repellent Lotion   ', 39, 39, '', '50 ml ', 'missingimagegr200.png', 190, 0, 'Active'),
(589, 4202, 'Baba Ramdev Patanjali Gulab Jal   ', 25, 25, '', '120 ml ', 'patanjali-gulab-jal-120-ml.png', 220, 0, 'Active'),
(722, 8068, 'Areev Melon &amp; Peach Mild Shampoo   ', 275, 275, '', '300 ml ', 'areev-melon-peach-mild-shampoo-v-300-ml-3.png', 200, 0, 'Active'),
(769, 8152, '18 Herbs K-Oil 100% Herbal Care   ', 275, 275, 'Hair Oil', '100 ml ', '18-herbs-18-herbs-k-oil-100-herbal-care-100-ml-1.png', 210, 100, 'Active'),
(797, 8273, 'Baba Ramdev Patanjali Kesh Kanti Anti Dandruff Hair Cleanser With Natural Conditioner   ', 110, 110, 'Anti Dandruff Shampoo', '200 ml ', 'baba-ramdev-patanjali-kesh-kanti-hair-cleanser-with-natural-conditioner-200-ml.png', 230, 22, 'Active'),
(901, 3936, 'Roots Hair Brush 2011   ', 175, 175, 'Hair Brush', '1 pc ', 'roots-hair-brush-2011-1-pc.png', 240, 5, 'Active'),
(918, 4273, 'Biotique Bio Henna Fresh Powder Hair Color   ', 199, 199, 'Powder', '90 g ', 'biotique-bio-henna-fresh-powder-hair-color-90-g.png', 250, 50, 'Active'),
(943, 7904, 'Brylcreem Anti Dandruff Aqua Oxy Hair Gel   ', 400, 40, 'Hair Gel', '50 g ', 'brylcreem-brylcreem-anti-dandruff-aqua-oxy-hair-gel-50-g.png', 260, 15, 'Active'),
(949, 5848, 'Ayur Natural Rajasthani Heena Mehendi   ', 11, 25, 'Mehendi.', '100 gm', 'ayur-natural-rajasthani-heena-mehendi-100-g.png', 270, 150, 'Active');




-- DROP TABLE IF EXISTS tomcat_users;
-- CREATE TABLE tomcat_users (
--   user_name varchar(20) NOT NULL PRIMARY KEY,
--   user_pass varchar(32) NOT NULL,
--   user_fio varchar(50) DEFAULT NULL,
--   user_ldap varchar(16) DEFAULT NULL,
--   email varchar(50) DEFAULT NULL,
--   group_name varchar(20) DEFAULT NULL,
--   ip varchar(16) DEFAULT NULL,
--   regdate date DEFAULT NULL,
--   update_ip varchar(16) DEFAULT NULL,
--   update_regdate date DEFAULT NULL,
--   CONSTRAINT tomcat_users_foreign_key_1 FOREIGN KEY (group_name) REFERENCES tomcat_users_group (group_name)
-- ) DEFAULT CHARSET=utf8;
-- DROP TABLE IF EXISTS tomcat_roles;
-- CREATE TABLE tomcat_roles (
--   role_name varchar(20) NOT NULL PRIMARY KEY,
--   role_description varchar(256) NULL
-- ) DEFAULT CHARSET=utf8;
-- DROP TABLE IF EXISTS tomcat_users_roles;
-- CREATE TABLE tomcat_users_roles (
--   user_name varchar(20) NOT NULL,
--   role_name varchar(20) NOT NULL,
--   PRIMARY KEY (user_name, role_name),
--   CONSTRAINT tomcat_users_roles_foreign_key_1 FOREIGN KEY (user_name) REFERENCES tomcat_users (user_name),
--   CONSTRAINT tomcat_users_roles_foreign_key_2 FOREIGN KEY (role_name) REFERENCES tomcat_roles (role_name)
-- ) DEFAULT CHARSET=utf8;
-- DROP TABLE IF EXISTS tomcat_users_group;
-- CREATE TABLE tomcat_users_group (
--   group_name varchar(20) NOT NULL PRIMARY KEY,
--   group_description varchar(256) NULL,
--   color varchar(7) DEFAULT '#BBBBBB'
-- ) DEFAULT CHARSET=utf8;